config/routes.rb
Rails.application.routes.draw do
  resources :webinars
  mount RedactorRails::Engine => '/redactor_rails'

  namespace :admin do
    root 'application#index'
  end

  # devise_for :users
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users do
    resources :skills, only: [:new, :create]
    post 'program_search', :on => :collection
    post 'desc_search', :on => :collection
    post 'name_search', :on => :collection
    post 'location_search', :on => :collection
  end

  root 'homes#index'

  resources :user_program_attendancies, only: [:new,
                                               :create,
                                               :destroy,
                                               :update,
                                               :edit,
                                               :index]

  resources :institutions, only: [:index, :show, :new] do
    collection do
      get :autocomplete
    end

    resources :programs do
      collection do
        get :autocomplete
      end

      resources :reviews, only: [:index,
                                 :create,
                                 :new,
                                 :destroy,
                                 :update,
                                 :edit,
                                 :show]

      resources :reviews, only: [:show] do
        member do
          put 'like', to: "reviews#upvote", defaults: { format: 'json' }
          put "dislike", to: "reviews#downvote", defaults: { format: 'json' }
        end
      end
    end
  end
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :reviews
  has_many :programs

  validates :name, presence: true
  validates :state, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :country, presence: true

  searchkick autocomplete: ['name']
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    respond_to do |format|
      format.html do
        @institution = Institution.find(params[:id])
        @reviews = @institution.reviews
        @programs = @institution.programs.order("title").page(
                                             params[:page]).per(5)
      end

      format.json do
        @institution = Institution.find(params[:id])
        programs = @institution.programs
        render json: [programs]
      end
    end
  end

  def autocomplete
    render json: Institution.search(params[:search],
                                           autocomplete: false,
                                           limit: 10).map do |institution|
      { name: institution.title, value: institution.id }
    end
  end

  def index
    if params[:search].present?
      @institutions = Institution.search params[:search], page: params[:page], per_page: 20
    else
      @institutions = Institution.order("name").page(
                                                params[:page]).per(10)
    end
  end

  def new
    if current_user
      if current_user.admin == true
        @institution = Institution.new
      else
        flash[:error] = 'You need to be an admin to create a institution'
        redirect_to root_path
      end
    end
  end

  def create
  end
end

app/views/institutions/_form.html.erb
<%= form_for @institution do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: 'Brown institution' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "redactor", placeholder: 'description' %>

  <%= f.label :city %>
  <%= f.text_field :city, placeholder: 'Providence' %>

  <%= f.label :state %>
  <%= f.text_field :state, placeholder: 'RI' %>

  <%= f.label :country %>
  <%= f.text_field :country, placeholder: 'US' %>

  <%= f.submit %>
<% end %>

app/views/institutions/_program.html.erb
<% @programs.each do |program| %>
<li><%= link_to "#{program.title}", institution_program_path(@institution, program) %></li>
<hr>
<% end %>
<%= paginate @programs %>

app/views/institutions/_review.html.erb
<% @reviews.each do |review| %>
  <div class="posts-feed-item row centered">
    <div class="small-1 medium-1 large-1 columns">
      <ul>
        <li>
          <% if review.user.profile_photo.file %>
            <p><%= image_tag review.user.profile_photo %></p>
          <% else %>
            <p><%= image_tag "default-profile.png" %></p>
          <% end %>
        </li>
        <li id="up-arrow-<%= review.id %>">
          <%= link_to like_institution_program_review_path(review.institution, review.program, review), class: "upvote_review",
           review: review.id, rating: review.rating,
           institution: review.institution.id do %>
            <i class="fi-arrow-up"></i>
          <% end  %>
        </li>
        <li class="votetext update-rating-<%= review.id %>"><%= review.score %></li>
        <li id="down-arrow-<%= review.id %>">
          <%= link_to dislike_institution_program_review_path(review.institution, review.program, review), class: "downvote_review",
           review: review.id, rating: review.rating,
           institution: review.institution.id do%>
             <i class="fi-arrow-down"></i>
           <% end %>
        </li>
      </ul>
    </div>

    <div class="small-10 medium-10 large-10 columns">
      <div class="program target row">
        <div class="large-8 columns">
          <ul>
            <li>
              Institution: <%= link_to "#{review.institution.name}", institution_path(review.institution) %>
            </li>
            <li>
              Program: <%= link_to "#{review.program.title}", institution_program_path(review.institution, review.program) %>
            </li>
          </ul>
        </div>
        <div class="large-4 columns">
          <ul>
            <li>
              Created from: <%= distance_of_time_in_words(Time.now, review.created_at) %> ago
            </li>
            <li>
              By: <%= link_to "#{review.user.first_name}", user_path(review.user) %>
            </li>
          </ul>
        </div>
      </div>
      <div class="title row">
        <div class="large-10 columns">
          <%= link_to "#{review.title}", institution_program_review_path(review.institution, review.program, review) %>
        </div>
        <div class="large-2 columns">
          Rating: <%= review.rating %>
        </div>
      </div>
      <div class="review content row">
        <%= raw review.content %>
      </div>
      <div class="row">
        <ul class="small-12 columns tiny button-group">
          <% if review.access_privilege(current_user) %>
            <li>
              <%= link_to 'Details', institution_program_review_path(review.institution, review.program, review), class: 'button small' %>
            </li>
            <li>
              <%= link_to 'edit',
              edit_institution_program_review_path(review.institution, review.program, review), class: 'button small' %>
            </li>
            <li>
              <%= link_to 'Delete',
              edit_institution_program_review_path(review.institution, review.program, review), method: :delete, class: 'button alert small' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="small-10 medium-10 large-1 columns"></div>
  </div>
  <hr>
<% end %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<h3 class="small-12 small-centered large-uncentered columns">Please choose the institution you are currently in:</h3>

<table class="small-12 small-centered large-uncentered columns">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= link_to institution.name, institution_path(institution) %></td>
        <td><%= institution.description %></td>
        <td><%= "#{institution.city},  #{institution.state},  #{institution.country}" %></td>
      </tr>
    <% end %>
  </tbody>

  <%= paginate @institutions %>
</table>

<% if current_user %>
  <% if current_user.admin == true %>
  <div class="button round secondary">
    <%= link_to 'add a new institution', new_institution_path %>
  </div>
  <% end %>
<% end %>

app/views/institutions/new.html.erb
<%= render 'form' %>

app/views/institutions/show.html.erb
<div class="large-12 large-centered columns content-box row" id="institution-show-page">
  <h3>
    <%= @institution.name %>
  </h3>
  <div class="large-8 columns large-centered searchBox" id="institution-show-searchbox">
    <div class="row">
        <%= form_tag("/institutions/#{@institution.id}/programs", method: 'get') do %>
          <%= text_field_tag :search, params[:search],placeholder: "search programs", class: 'form-control typeahead'%>
          <%= submit_tag "Search programs", name: nil, class: 'tiny button' %>
        <% end %>
    </div>
  </div>
  <hr>
    <%= render 'program' %>
  <hr>
    <div class="row users">
      <h3>Students of this school</h3>
      <% find_users_of(@institution).each do |user| %>
      <%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %>
      <% end %>
    </div>
  <hr>
    <%= render 'review' %>
  <ul class="small-8 columns button-group">
    <li>
      <%= link_to 'Back', institutions_path, class: 'button' %>
    </li>
  </ul>
</div>