config/routes.rb
Rails.application.routes.draw do
  resources :webinars
  mount RedactorRails::Engine => '/redactor_rails'

  namespace :admin do
    root 'application#index'
  end

  # devise_for :users
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users do
    resources :skills, only: [:new, :create]
    post 'program_search', :on => :collection
    post 'desc_search', :on => :collection
    post 'name_search', :on => :collection
    post 'location_search', :on => :collection
  end

  root 'homes#index'

  resources :user_program_attendancies, only: [:new,
                                               :create,
                                               :destroy,
                                               :update,
                                               :edit,
                                               :index]

  resources :institutions, only: [:index, :show, :new] do
    collection do
      get :autocomplete
    end

    resources :programs do
      collection do
        get :autocomplete
      end

      resources :reviews, only: [:index,
                                 :create,
                                 :new,
                                 :destroy,
                                 :update,
                                 :edit,
                                 :show]

      resources :reviews, only: [:show] do
        member do
          put 'like', to: "reviews#upvote", defaults: { format: 'json' }
          put "dislike", to: "reviews#downvote", defaults: { format: 'json' }
        end
      end
    end
  end
end

app/models/webinar.rb
class Webinar < ActiveRecord::Base
  	belongs_to :user

  	validates_presence_of :name
  	validates_presence_of :filepath

  	mount_uploader :filepath, UserFileUploader
  	
end

app/controllers/webinars_controller.rb
class WebinarsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_webinar, only: [:show, :edit, :update, :destroy]

  # GET /webinars
  # GET /webinars.json
  def index
    if current_user.admin
      @webinars = Webinar.all
    else
      @webinars = Webinar.where(:user_id => current_user.id)
    end
  end

  # GET /webinars/1
  # GET /webinars/1.json
  def show
    @webinar = Webinar.find(params[:id])
    # @webinar.filepath = "Big_Buck_Bunny.mp4"

  end

  # GET /webinars/new
  def new
    @webinar = Webinar.new
    @users = User.all
  end

  # GET /webinars/1/edit
  def edit
  end

  # POST /webinars
  # POST /webinars.json
  def create

    @webinar = Webinar.new
    @webinar.name = params[:webinar][:name]
    @webinar.participates = params[:webinar][:participates]
    @webinar.user_id = current_user.id
    @webinar.filepath = params[:webinar][:filepath]
    
    respond_to do |format|
      if @webinar.save
        format.html { redirect_to @webinar, notice: 'Webinar was successfully created.' }
        format.json { render :show, status: :created, location: @webinar }
        # render :json => @webinar, :notice => "Webinar was successfully created."
      else
        format.html { render :new }
        format.json { render json: @webinar.errors, status: :unprocessable_entity }
        # render :json => "Create Fail, try again"
      end
    end
  end

  # PATCH/PUT /webinars/1
  # PATCH/PUT /webinars/1.json
  def update
    respond_to do |format|
      if @webinar.update(update_params)

        format.html { redirect_to @webinar, notice: 'Webinar was successfully updated.' }
        format.json { render :show, status: :ok, location: @webinar }
      else
        format.html { render :edit }
        format.json { render json: @webinar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webinars/1
  # DELETE /webinars/1.json
  def destroy
    @webinar.destroy
    respond_to do |format|
      format.html { redirect_to webinars_url, notice: 'Webinar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webinar
      @webinar = Webinar.find(params[:id])
    end

    def update_params
      params.require(:webinar).permit(:name, :filepath, :participates => [])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def webinar_params
      params.require(:webinar).permit(:name, :filepath, :participates, :user_id)
    end

end

app/helpers/webinars_helper.rb
module WebinarsHelper
end

app/views/webinars/_form.html.erb
<%= simple_form_for(@webinar) do |f| %>
  	<%= f.error_notification %>

  	<div class="form-group">
    	<%= f.input :name %>
    </div>

    <div class="form-group">
		  <%= f.label :participates %>

      <%= f.select :participates, User.all.collect{|user| [user.email, user.id]}, {}, :class => "chosen-select", :multiple =>true %>
    </div>
    </br>
    <div class="form-group">
      <%= f.label :filepath, 'Video' %>
      <br />
    	<%= f.file_field :filepath %>
    </div>

  	<div class="form-actions webinar-create">
    	<%= f.button :submit %>
  	</div>

<% end %>

<script type="text/javascript">
	$(function(){
	    var config = {
	        '.chosen-select': {},
	        '.chosen-select-deselect': { allow_single_deselect: true },
	        '.chosen-select-no-single': { disable_search_threshold: 10 },
	        '.chosen-select-no-results': { no_results_text: 'Oops, nothing found!' },
	        '.chosen-select-width': { width: "100%" }
    	}
	    for (var selector in config) {
	        $(selector).chosen(config[selector]);
	    }

	});
</script>

app/views/webinars/edit.html.erb
<div class="container padding">
	<h1>Editing Webinar</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @webinar %> | <%= link_to 'Back', webinars_path %>
</div>

app/views/webinars/index.html.erb
<div class="container padding">
<p id="notice"><%= notice %></p>

<h1>Webinars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Filepath</th>
      <th>Participates</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webinars.each do |webinar| %>
      <tr>
        <td><%= webinar.name %></td>
        <td><%= webinar.filepath %></td>
        <td>
            <% participates = webinar.participates %>
            <% participates.each do |participate| %>
              <% if participate != "" %>
                <% participate_int = participate.to_i %>
                <% if(User.find_by_id(participate_int)) %>
                  <%= User.find_by_id(participate_int).email %>
                <% end %>
              <% end %>
              <br>
            <% end %>
        </td>
        <td>
          <% if webinar.user != nil %>
          <%= webinar.user.first_name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', webinar %></td>
        <td><%= link_to 'Edit', edit_webinar_path(webinar) %></td>
        <td><%= link_to 'Destroy', webinar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webinar', new_webinar_path, class: 'tiny button radius'  %>
</div>

app/views/webinars/new.html.erb
<div class="container padding">
	<h1>New Webinar</h1>
	<%= render 'form' %>

	<div class="modal inmodal fade" id="createWebinarModal" tabindex="-1" role="dialog" aria-hidden="true">
		<div style="background: white none repeat scroll 0 0; margin-left: auto; margin-right: auto;  margin-top: 200px; text-align: center; width: 94px;">
			<img src="/assets/loading.gif">
		</div>
	</div>

	<%= link_to 'Back', webinars_path,  :class => "button"%>
</div>

<script type="text/javascript">
	$(function() {
		$(".webinar-create .button").click(function(){
			$("#createWebinarModal").modal('show');
		})
	})
</script>

app/views/webinars/show.html.erb
<div class="container padding">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @webinar.name %>
  </p>

  <p>
    <strong>Video:</strong>
    <br />
    <%= video_tag @webinar.filepath, :size => "300x200", :controls => true %>
  </p>

  <p>
    <strong>Participates:</strong>
    <br />
    <% participates = @webinar.participates %>
    <% participates.each do |participate| %>
    	<% if participate != "" %>
  	  	<% participate_int = participate.to_i %>
  	  	<p><%= User.find_by_id(participate_int).email %></p>
    	<% end %>
    <% end %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @webinar.user.first_name %>
  </p>

  <%= link_to 'Edit', edit_webinar_path(@webinar) %> |
  <%= link_to 'Back', webinars_path %>
</div>