config/routes.rb
Rails.application.routes.draw do
  resources :webinars
  mount RedactorRails::Engine => '/redactor_rails'

  namespace :admin do
    root 'application#index'
  end

  # devise_for :users
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users do
    resources :skills, only: [:new, :create]
    post 'program_search', :on => :collection
    post 'desc_search', :on => :collection
    post 'name_search', :on => :collection
    post 'location_search', :on => :collection
  end

  root 'homes#index'

  resources :user_program_attendancies, only: [:new,
                                               :create,
                                               :destroy,
                                               :update,
                                               :edit,
                                               :index]

  resources :institutions, only: [:index, :show, :new] do
    collection do
      get :autocomplete
    end

    resources :programs do
      collection do
        get :autocomplete
      end

      resources :reviews, only: [:index,
                                 :create,
                                 :new,
                                 :destroy,
                                 :update,
                                 :edit,
                                 :show]

      resources :reviews, only: [:show] do
        member do
          put 'like', to: "reviews#upvote", defaults: { format: 'json' }
          put "dislike", to: "reviews#downvote", defaults: { format: 'json' }
        end
      end
    end
  end
end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :institution
  has_many :reviews
  has_many :skills
  has_many :user_program_attendancies
  has_many :users, through: :user_program_attendancies

  validates :title, presence: true

  searchkick
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_filter :authenticate_user!
  def show
    @program = Program.find(params[:id])
    @institution = @program.institution
    @reviews = @program.reviews
  end

  def index
    if params[:search].present?
      @programs = Program.search params[:search], page: params[:page], per_page: 20
    else
      @programs = Program.order("title").page(params[:page]).per(10)
    end
  end
end

app/views/programs/_form.html.erb
<%= form_for [@institution, @program] do |f| %>

  <%= f.label :title %>
  <%= f.collection_select :title, Program.all, :title, :title %>

  <%= f.submit 'Add your program', class: 'button tiny' %>
<% end %>

app/views/programs/_review.html.erb
<% @reviews.each do |review| %>
  <div class="posts-feed-item row centered">
    <div class="large-1 columns">
      <ul>
        <li>
          <% if review.user.profile_photo.file %>
            <p><%= image_tag review.user.profile_photo %></p>
          <% else %>
            <p><%= image_tag "#" %></p>
          <% end %>
        </li>
        <li id="up-arrow-<%= review.id %>">
          <%= link_to like_institution_program_review_path(review.institution, review.program, review), class: "upvote_review",
           review: review.id, rating: review.rating,
           institution: review.institution.id do %>
            <i class="fi-arrow-up"></i>
          <% end  %>
        </li>
        <li class="votetext update-rating-<%= review.id %>"><%= review.score %></li>
        <li id="down-arrow-<%= review.id %>">
          <%= link_to dislike_institution_program_review_path(review.institution, review.program, review), class: "downvote_review",
           review: review.id, rating: review.rating,
           institution: review.institution.id do%>
             <i class="fi-arrow-down"></i>
           <% end %>
        </li>
      </ul>
    </div>

    <div class="large-10 columns">
      <div class="program target row">
        <div class="large-8 columns">
          <ul>
            <li>
              Institution: <%= link_to "#{review.institution.name}", institution_path(review.institution) %>
            </li>
            <li>
              Program: <%= link_to "#{review.program.title}", institution_program_path(review.institution, review.program) %>
            </li>
          </ul>
        </div>
        <div class="large-4 columns">
          <ul>
            <li>
              Created from: <%= distance_of_time_in_words(Time.now, review.created_at) %> ago
            </li>
            <li>
              By: <%= review.user.first_name %>
            </li>
          </ul>
        </div>
      </div>
      <div class="title row">
        <div class="large-10 columns">
          <%= link_to "#{review.title}", institution_program_review_path(review.institution, review.program, review) %>
        </div>
        <div class="large-2 columns">
          Rating: <%= review.rating %>
        </div>
      </div>
      <div class="review content row">
        <%= raw review.content %>
      </div>
      <div class="row">
        <ul class="small-12 columns small button-group">
          <% if review.access_privilege(current_user) %>
            <li>
              <%= link_to 'Details', institution_program_review_path(review.institution, review.program, review), class: 'button small' %>
            </li>
            <li>
              <%= link_to 'edit',
              edit_institution_program_review_path(review.institution, review.program, review), class: 'button small' %>
            </li>
            <li>
              <%= link_to 'Delete',
              edit_institution_program_review_path(review.institution, review.program, review), method: :delete, class: 'button alert small' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="large-1 columns"></div>
  </div>
  <hr>
<% end %>

app/views/programs/index.html.erb
<% @programs.each do |program| %>
  <li>
    <%= link_to "#{program.title}", institution_program_path(program.institution, program) %>
  </li>
<% end %>

<%= paginate @programs %>

app/views/programs/show.html.erb
<h3><%= @institution.name %></h3>

<%= render 'review' %>

<hr>
<ul class="small-8 columns button-group">
  <li>
    <%= link_to 'Back', institution_path(@institution), class: 'button' %>
    <%= link_to 'Add a review', new_institution_program_review_path(@institution, @program) %>
  </li>
</ul>