config/routes.rb
Rails.application.routes.draw do
  resources :webinars
  mount RedactorRails::Engine => '/redactor_rails'

  namespace :admin do
    root 'application#index'
  end

  # devise_for :users
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users do
    resources :skills, only: [:new, :create]
    post 'program_search', :on => :collection
    post 'desc_search', :on => :collection
    post 'name_search', :on => :collection
    post 'location_search', :on => :collection
  end

  root 'homes#index'

  resources :user_program_attendancies, only: [:new,
                                               :create,
                                               :destroy,
                                               :update,
                                               :edit,
                                               :index]

  resources :institutions, only: [:index, :show, :new] do
    collection do
      get :autocomplete
    end

    resources :programs do
      collection do
        get :autocomplete
      end

      resources :reviews, only: [:index,
                                 :create,
                                 :new,
                                 :destroy,
                                 :update,
                                 :edit,
                                 :show]

      resources :reviews, only: [:show] do
        member do
          put 'like', to: "reviews#upvote", defaults: { format: 'json' }
          put "dislike", to: "reviews#downvote", defaults: { format: 'json' }
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :skills
  has_many :user_program_attendancies
  has_many :programs, through: :user_program_attendancies
  has_many :webinars

  validates_presence_of :first_name
  validates_presence_of :last_name

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  mount_uploader :profile_photo, ProfilePhotoUploader

  def access_privilege(user)
    (user) && ((user.id == id) || (user.admin))
  end

  def check_admin(user)
    user.admin
  end

  def self.search(str)
    terms = str.split
    query = terms.map { |terms| "name like '%#{term}'" }.join( "OR" )
    User.where(query)
  end

end

app/controllers/users_controller.rb
require 'quickblox'

class UsersController < ApplicationController
  before_filter :authenticate_user!
  def index
    if params[:search].present?
      search = params[:search]
      n_page = params[:page]
      @users = User.search(search).order("last_name").page(n_page).per(9)
    else
      @users = User.order("last_name").page(params[:page]).per(10)
      respond_to do |format|
        format.html do
          @reviews = Review.order("updated_at").page(params[:page]).per(10)
          @users = User.order("last_name").page(params[:page]).per(10)
        end

        format.json do
          categories = []
          @users.each do |user|
            categories << "#{user.first_name} #{user.last_name}"
          end

          series = []

          Category.all.each do |category|
            new_series = Hash.new
            new_series[:name] = category.name

            new_series[:data] = []
            @users.each do |user|
              skill_list = user.skills.where(category_id: category.id)
              score = 0
              skill_list.each do |skill|
                score = score + skill.points
              end
              new_series[:data] << score
            end
            series << new_series
          end

          render json: [categories, series]
        end
      end
    end

    @webinars = Webinar.order("created_at DESC").limit(4)

    @paticipants_list = []

    @webinars.each do |webinar|
      participates = webinar.participates
      pat_list = []

      participates.each do |pat|
        if pat != ''
          pat_list << User.where(:id => pat.to_i)
        end
      end
      @paticipants_list << pat_list

    end

    @programs_list = []

    Institution.all.each do |institution|
      new_series = Hash.new

      new_series[:name] = institution.name
      new_series[:data] = []

      Program.where(:institution => institution).each do |ins_p|
        new_series[:data] << ins_p.title
      end

      @programs_list << new_series
    end

  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.page(params[:page]).per(5)
    @skills = @user.skills
    @programs = @user.user_program_attendancies
    @skill = Skill.new
    @program = Program.new
    @user_program_attendancy = UserProgramAttendancy.new
    @programs_finished = @user.user_program_attendancies.where('end_date < ?',
                                                               Time.now)
    @programs_planning = @user.user_program_attendancies.where(
                                                              'start_date > ?',
                                                              Time.now)
    @programs_inprogress =
    @user.user_program_attendancies.where('start_date < ? AND end_date > ?',
                                          Time.now, Time.now)

    respond_to do |format|
      format.html do
        @user = User.find(params[:id])
        @reviews = @user.reviews.page(params[:page]).per(5)
      end

      format.json do
        @user = User.find(params[:id])
        @skills = @user.skills
        @category_list = []
        @skill_points_output = Hash.new
        @skills.each do |skill|
          category_name = Category.find(skill[:category_id]).name
          if @skill_points_output.has_key?(category_name) == false
            @skill_points_output["#{category_name}"] = skill[:points]
          else
            @skill_points_output["#{category_name}"] = @skill_points_output["#{category_name}"] +
            skill[:points]
          end
        end
        user_skill_output = @skill_points_output
        timeline_output = []
        @user.user_program_attendancies.each do |user_program_attendancy|
          timeline_output << [user_program_attendancy, user_program_attendancy.user, user_program_attendancy.program]
        end
        user_description = @user.description

        # The json object 'user_skill_output' is for the web-map js.
        # The json object 'timeline_output' is for the timeline js.
        # The json object 'skills_output' is for the web-user-skills
        render json: [user_skill_output, timeline_output, user_description]
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if !@user.access_privilege(current_user)
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Successfully updated!'
      redirect_to user_path(@user)
    else
      flash[:alert] = 'Something went wrong!'
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user = current_user
      @user.destroy
      flash[:success] = 'User deleted'
      redirect_to root_path
    else
      flash[:alert] = 'You don\'t have the permission'
      redirect_to user_path current_user
    end
  end

  def program_search
    @result = []
    key = params[:program]

    program = Program.where("lower(title) like lower (?)","#{key}")
    
    user_program_attendancies = UserProgramAttendancy.where(:program_id => program[0].id)

    user_ids = []
    programs = []

    user_program_attendancies.each do |user_program_attendancy|
      
      if !(user_ids.include?(user_program_attendancy.user_id))
        user_ids << user_program_attendancy.user_id
      end
    end
    
    user_ids.each do |user_id|
      search_temp = Hash.new

      user_temp = User.find_by_id(user_id)
      
      program_output = []

      user_temp.user_program_attendancies.each do |user_program_attendancy|
        program_output << [user_program_attendancy, user_program_attendancy.program, user_program_attendancy.program.institution]
      end

      search_temp[:user] = user_temp
      search_temp[:programs] = program_output
      @result << search_temp
    end

    render :json => @result, :status => 200
    
  end

  def desc_search
    @result = []
    key = params[:description]

    users = []
    programs = []

    users = User.where("lower(description) like lower(?)", "%#{key}%")

    users.each do | u |
      search_temp = Hash.new
      
      program_output = []

      u.user_program_attendancies.each do |user_program_attendancy|
        program_output << [user_program_attendancy, user_program_attendancy.program, user_program_attendancy.program.institution]
      end

      search_temp[:user] = u
      search_temp[:programs] = program_output
      @result << search_temp
    end

    render :json => @result, :status => 200

  end

  def name_search
    @result = []
    keys = params[:username].split

    users = []
    programs = []

    if keys.length > 1 
      users = User.where("lower(first_name) like lower(?) and lower(last_name) like lower(?) ", "%#{keys[0]}%", "%#{keys[2]}%")
    else 
      users = User.where("lower(first_name) like lower(?) OR lower(last_name) like lower(?) ", "%#{keys[0]}%", "%#{keys[0]}%")
    end

    users.each do | u |
      search_temp = Hash.new
      
      program_output = []

      u.user_program_attendancies.each do |user_program_attendancy|
        program_output << [user_program_attendancy, user_program_attendancy.program, user_program_attendancy.program.institution]
      end

      search_temp[:user] = u
      search_temp[:programs] = program_output
      @result << search_temp
    end

    render :json => @result, :status => 200
  end

  def location_search
    @result = []
    key = params[:location]

    users = []
    programs = []

    users = User.where("lower(location) like lower(?)", "%#{key}%")

    users.each do | u |
      search_temp = Hash.new
      
      program_output = []

      u.user_program_attendancies.each do |user_program_attendancy|
        program_output << [user_program_attendancy, user_program_attendancy.program, user_program_attendancy.program.institution]
      end

      search_temp[:user] = u
      search_temp[:programs] = program_output
      @result << search_temp
    end

    render :json => @result, :status => 200
  end

  protected

  def user_params
    params.require(:user).permit(
      :email,
      :first_name,
      :last_name,
      :location,
      :profile_photo,
      :description
    )
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :profile_photo %>
  <%= f.file_field :profile_photo %>

  <%= f.submit 'Accept Changes', class: 'small button' %>
  <%= link_to 'Back', user_path(@user), class: 'small button' %>
<% end %>

app/views/users/edit.html.erb
<div class="large-6 large-centered columns">
  <%- if @user.errors.present? -%>
  <div class="alert-box alert" data-alert>
    <ul>
      <%- @user.errors.full_messages.each do |error| -%>
        <li><%= error %></li>
      <%- end %>
    </ul>
  </div>
  <%- end %>
</div>
<%- if @user.access_privilege(current_user) -%>
  <div class="text-center">
    <h3>Edit Account information</h3>
  </div>
  <div class="large-6 large-centered columns panel">
  <%= render 'form' %>
<%- else %>
  You do not have permission to edit this user's information
<%- end -%>

app/views/users/show.html.erb
<div class="large-12 large-centered columns content-box row" id="content-box">
  <div class="row user-info-section">
    <div class="medium-3 large-3 columns">
      <% if @user.profile_photo.file %>
        <p><%= image_tag @user.profile_photo %></p>
      <% else %>
        <p><%= image_tag "default-profile.png", width: 128, height: 128 %></p>
      <% end %>
      <p><b><%= @user.first_name if @user.first_name %> <%= @user.last_name if @user.last_name %></b></p>
      <p><%= @user.location if @user.location %></p>

      <% if @user.access_privilege(current_user) %>
        <ul class="stack button-group radius">
          <li><%= link_to "Edit Information", edit_user_path(@user), class: 'tiny button radius' %></li>
          <% if @user.check_admin(current_user) %>
          <li><%= link_to "Delete Account", user_path(@user), method: :delete, class: 'tiny button radius' %></li>
          <% end %>
          <li><%= link_to "Organize programs", user_program_attendancies_path, class: 'tiny button radius' %></li>
          <li><%= link_to "Create Webinar", webinars_path, class: 'tiny button radius' %></li>
        </ul>
      <% end %>
    </div>

    <div class="medium-6 large-6 columns" id="content-middle">
      <div class="row" id="container-user-skill-columns"></div>
      <p id="content-middle-self-intro-title"><%= @user.first_name if @user.first_name %>'s center:</p>
      <div class="row" id="user_show">
        <% if @user.description %>
          <%= truncate(@user.description,
                       length: 300,
                       escape: false){
                       link_to 'More', '#', id: "user_profile_intro"
                       } %>
        <% else %>
        <p>
          He did\'t leave anything.
        </p>
        <% end %>
      </div>
      <% if @skills %>
        <div class="row">
          <p>
            Skills:
            <% @skills.each do |skill| %>
              <span data-tooltip aria-haspopup="true" class="has-tip" title="<%= skill.name %>">
                <% if(skill.category) %>
                  <i class="<%= skill.category.icons %>"></i>
                <% end %>
              </span>
            <% end %>
          </p>
        </div>
      <% else %>
        Get some new skills!
      <% end %>
    </div>

    <div class="medium-3 large-3 columns" id="user_progress">
      <% if @programs %>
        <p><%= @user.first_name if @user.first_name %>'s programs:</p>
        <div class="row program-learned">
          <ul>
            <li class="progress-title">Programs finished:</li>
            <% if @programs_finished %>
              <% @programs_finished.each do |user_program_attendancy| %>
                <li><%= user_program_attendancy.program.title %></li>
              <% end %>
            <% else %>
              <li>nothing here.</li>
            <%end %>

            <li class="progress-title">Programs in-progress:</li>
            <% if @programs_inprogress %>
              <% @programs_inprogress.each do |user_program_attendancy| %>
                <li><%= user_program_attendancy.program.title %></li>
                <div class="progress small-12 large-12
                  secondary alert radius round" style="inline">
                  <span class="meter"
                        style="width: <%= (Date.today - user_program_attendancy.start_date)/
                        ((user_program_attendancy.end_date -
                        user_program_attendancy.start_date).to_f)*100.round(0) %>%">
                        <p class="percent"><%= ((Date.today -
                         user_program_attendancy.start_date)/
                         ((user_program_attendancy.end_date -
                         user_program_attendancy.start_date).to_f)*100).round %>%</p></span>
                </div>
              <% end %>
            <% else %>
              <li>nothing here.</li>
            <% end %>

            <li class="progress-title">Programs planned:</li>
            <% if @programs_planning %>
              <% @programs_planning.each do |user_program_attendancy| %>
                <li><%= user_program_attendancy.program.title %></li>
              <% end %>
            <% else %>
              <li>nothing here.</li>
            <% end %>
          </ul>
        </div>
      <% else %>
        Get some new skills!
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row timeline" id="timeline-embed" style="min-height: 400px;"></div>

<!-- the following section is for skill-planner -->
  <hr>
  <div class="row">
    <div class="large-7 columns" id="container-user-skill-webmap"></div>
    <% if @user.access_privilege(current_user) %>
      <div class="large-5 columns skill-planner">
        <ul class="accordion" data-accordion>
          <li class="accordion-navigation">
            <a href="#panel1a">Add a skill</a>
            <div id="panel1a" class="content active">
              <%= render 'skills/form' %>
            </div>
          </li>
          <li class="accordion-navigation">
            <a href="#panel2a">Add a program</a>
            <div id="panel2a" class="content">
              <%= form_for @user_program_attendancy do |f| %>
                <%= f.label :'Choose an institution' %>
                <%= f.collection_select(:location, Institution.all, :id, :name, prompt: true) %>
                <%= f.label :'Choose an program' %>
                <%= f.collection_select(:program_id, Program.all, :id, :title, prompt: true) %>
                <!-- set up a hard-coded select box with ONE empty option that says "Select an instutution above" -->
                <div class="large-12 columns">
                  <div class="large-6 columns">
                    <%= f.label :'select start date' %>
                    <%= date_select :user_program_attendancy, :start_date %>
                  </div>

                  <div class="large-6 columns">
                    <%= f.label :'select end date' %>
                    <%= date_select :user_program_attendancy, :end_date %>
                  </div>
                </div>

                <%= f.label :'please provide an image or video url' %>
                <%= f.text_field :url, placeholder: "provide an image or video link!" %>

                <%= f.submit 'Add your program', class: 'button tiny' =%>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
  <!-- skill-planner section ends here -->
  <hr>

  <!--  User's post section -->
  <% if @reviews %><h4><%= @user.first_name %>'s Posts</h4><% end %>
  <% if @reviews %>
    <% @reviews.each do |review| %>
      <div class="posts-feed-item row centered">
        <div class="small-1 medium-1 large-1 columns">
          <ul>
            <li>
              <% if @user.profile_photo.file %>
                <p><%= image_tag @user.profile_photo %></p>
              <% else %>
                <p><%= image_tag "default-profile.png" %></p>
              <% end %>
            </li>
            <li id="up-arrow-<%= review.id %>">
              <%= link_to like_institution_program_review_path(review.institution, review.program, review), class: "upvote_review",
               review: review.id, rating: review.rating,
               institution: review.institution.id do %>
                <i class="fi-arrow-up"></i>
              <% end  %>
            </li>
            <li class="votetext update-rating-<%= review.id %>"><%= review.score %></li>
            <li id="down-arrow-<%= review.id %>">
              <%= link_to dislike_institution_program_review_path(review.institution, review.program, review), class: "downvote_review",
               review: review.id, rating: review.rating,
               institution: review.institution.id do%>
                 <i class="fi-arrow-down"></i>
               <% end %>
            </li>
          </ul>
        </div>

        <div class="small-10 medium-10 large-10 columns">
          <div class="program target row">
            <div class="large-8 columns">
              <ul>
                <li>
                  Institution: <%= link_to "#{review.institution.name}", institution_path(review.institution) %>
                </li>
                <li>
                  Program: <%= link_to "#{review.program.title}", institution_program_path(review.institution, review.program) %>
                </li>
              </ul>
            </div>
            <div class="large-4 columns">
              <ul>
                <li>
                  Created from: <%= distance_of_time_in_words(Time.now, review.created_at) %> ago
                </li>
                <li>
                  By: <%= @user.first_name %>
                </li>
              </ul>
            </div>
          </div>
          <div class="title row">
            <div class="large-10 columns">
              <%= link_to "#{review.title}", institution_program_review_path(review.institution, review.program, review) %>
            </div>
            <div class="large-2 columns">
              Rating: <%= review.rating %>
            </div>
          </div>
          <div class="review content row">
            <%= raw review.content %>
          </div>
          <div class="row">
            <ul class="small-12 columns tiny button-group">
              <% if review.access_privilege(current_user) %>
                <li>
                  <%= link_to 'Details', institution_program_review_path(review.institution, review.program, review), class: 'button small' %>
                </li>
                <li>
                  <%= link_to 'edit',
                  edit_institution_program_review_path(review.institution, review.program, review), class: 'button small' %>
                </li>
                <li>
                  <%= link_to 'Delete',
                  edit_institution_program_review_path(review.institution, review.program, review), method: :delete, class: 'button alert small' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="small-10 medium-10 large-1 columns"></div>
      </div>
      <hr>
    <% end %>
    <%= paginate @reviews %>
  <% end %>